services:
  gwdb:
    build: .
    image: gwdb:latest
    container_name: gwdb
    ports:
      - "8080:3142"
    depends_on:
      - mariadb
      - postgres
    networks:
      - gwdb-network
    volumes:
      - ./:/var/www/html
    environment:
      HOME: /tmp
      TOKEN: 123

      DB_MYSQL_HOST: mariadb
      DB_MYSQL_USER: admin
      DB_MYSQL_PASS: admin
      DB_MYSQL_PORT: 3306

      DB_PGSQL_HOST: postgres
      DB_PGSQL_USER: admin
      DB_PGSQL_PASS: admin
      DB_PGSQL_PORT: 5432
      DB_PGSQL_ADMIN_NAME: postgres
    user: "${UID:-1000}:${GID:-1000}"

  mariadb:
    image: mariadb:11
    container_name: gwdb_mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: gwdb
    networks:
      - gwdb-network
    ports:
      - "8306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  postgres:
    image: postgres:16
    container_name: gwdb_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    networks:
      - gwdb-network
    ports:
      - "8432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: gwdb_phpmyadmin
    restart: always
    depends_on:
      - mariadb
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: gwdb
    networks:
      - gwdb-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: gwdb_pgadmin
    restart: always
    depends_on:
      - postgres
    ports:
      - "8082:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - gwdb-network

networks:
  gwdb-network:

volumes:
  db_data:
  pg_data: